language: python
python:
  - "3.7"
dist: xenial
cache: pip
sudo: false

services:
  - docker

before_install:
- docker pull allena29/yangvoodoo:devel
- docker run -d -i --name working allena29/yangvoodoo:devel /bin/sh
- docker exec -i working /bin/sh -c "git config --global user.email travis@builder"
- docker exec -i working /bin/sh -c "git pull"
- docker exec -i working /bin/sh -c "git status"
- docker ps -a

install:
  - echo "skip pip install"

script:
  - docker exec -i working /bin/sh -c "cd /working; git checkout $TRAVIS_COMMIT"
  - docker exec -i working /working/test-in-docker.sh
